name: Check Jira Ticket Format In Commits

on:
  pull_request:

jobs:
  test_jira_ticket:
    uses: datafy-io/devops_tools/.github/workflows/test_jira_id_in_pr.yml@avner/DT-6431-support-for-2-jira-tickets-in-pr